### PR TITLE
Ignored .cache files from repo.

### PR DESCRIPTION
**Pull request by apap04**
Now, cache files will be ignored.

### CODE REVIEW

**Comment by sr229** [comment]
don't forget to remove the .cache files if you can :wink:

**Comment by apap04** [comment]
They're removed when they are added in .gitignore

**Comment by apap04** [comment]
ok :b:

**Comment by apap04** [comment]
image
the green shows that a file was added then the red is after it so basically the files (were) are already deleted by .gitignore

**Comment by apap04** [comment]
😩 👌 💧 k

**Pull request merged**
